// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/apps/product-options": {
    params: {};
  };
  "/upload-swatch-image": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/options/assets": {
    params: {};
  };
  "/app/options/:id": {
    params: {
      "id": string;
    };
  };
  "/app/options/new": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/options": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/apps/product-options" | "/upload-swatch-image" | "/auth/login" | "/auth/*" | "/app" | "/app/options/assets" | "/app/options/:id" | "/app/options/new" | "/app/additional" | "/app/options";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/apps.product-options.jsx": {
    id: "routes/apps.product-options";
    page: "/apps/product-options";
  };
  "routes/upload-swatch-image.jsx": {
    id: "routes/upload-swatch-image";
    page: "/upload-swatch-image";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/options/assets" | "/app/options/:id" | "/app/options/new" | "/app/additional" | "/app/options";
  };
  "routes/app.options_.assets.jsx": {
    id: "routes/app.options_.assets";
    page: "/app/options/assets";
  };
  "routes/app.options_.$id.jsx": {
    id: "routes/app.options_.$id";
    page: "/app/options/:id";
  };
  "routes/app.options_.new.jsx": {
    id: "routes/app.options_.new";
    page: "/app/options/new";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.options.jsx": {
    id: "routes/app.options";
    page: "/app/options";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/apps.product-options": typeof import("./app/routes/apps.product-options.jsx");
  "routes/upload-swatch-image": typeof import("./app/routes/upload-swatch-image.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.options_.assets": typeof import("./app/routes/app.options_.assets.jsx");
  "routes/app.options_.$id": typeof import("./app/routes/app.options_.$id.jsx");
  "routes/app.options_.new": typeof import("./app/routes/app.options_.new.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.options": typeof import("./app/routes/app.options.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};