# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e785ee29f4caece99aaa8d733b50f46"
application_url = "https://koapack-product-options-manager.onrender.com"
embedded = true
name = "product-options-manager"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_cart_transforms,write_files,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://koapack-product-options-manager.onrender.com/auth/callback",
  "https://koapack-product-options-manager.onrender.com/auth/shopify/callback",
  "https://koapack-product-options-manager.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://koapack-product-options-manager.onrender.com/apps/product-options"
subpath = "product-options"
prefix = "apps"
